### ISSUE TITLE
page de login

### ISSUE THREAD

**Issue by araviart** [araviart/COMP_ESCRIME#9]
avec responsive + lien avec la bd

**Comment by krshmt** [comment]
fin de la page de login. il reste plus que le responsive. l'objectif du responsive, enlever l'image pour avoir plus de place ou soit, mettre l'image au dessus de la partie connexion

**Comment by krshmt** [comment]
le login est terminé avec quelques modifications et le responsive est réalisé

**Comment by krshmt** [comment]
l'issue est réouvert car le lien avec la bd n'est pas réalisé
